### ISSUE TITLE
Striking rules within house of lords

### ISSUE THREAD

**Issue by HarrisonBacordo** [seanKenkeremath/lords-and-lads#17]
If there are more multiple seats in the house of lords, can the lords hit whichever lord nail they wish? Or must the lords continue to hammer the same nail together until it is considered complete before moving onto the next lord nail?

**Comment by seanKenkeremath** [comment]
@HarrisonBacordo They can hit whichever nail they choose. And if a lord finishes any center nail they also have the option to demote another lord.
