### ISSUE TITLE
Bent nails can stall the game

### ISSUE THREAD

**Issue by seanKenkeremath** [seanKenkeremath/lords-and-lads#18]
I've played a number of games recently where bent nails really held up the game. Especially bent Lord nails.

As a lad, a bent nail can really take you out of the running, and when Lord nails get bent it can basically just prevent the game from ending. A lot of times people end up just trying to hit the nail out to reset it which is no fun and also not the safest.

Currently, if 2 lads collude they can reset their own nails by taking advantage of the penalty rules for each other:

```
A Lad strikes another Lad's nail
If a Lad strikes another Lad's nail, the Lad whose nail was struck chooses one of the following actions:

Do nothing
Reset their own nail
Swap nails with the Lad who struck the nail
Make the Lad who struck the nail drink 3
Get one free strike at that Lad's nail before play continues (at least one flip must still be performed)
```

This is fine, but it requires another lad to help you and is kind of convoluted. Effectively in this scenario you are just skipping your turn to reset the nail

There is no mechanic that resets a bent Lord nail.

**Potential Suggestion**

1.  A lad should be able to skip their turn at any point to reset their nail to it's starting height/position (or just put a new nail in)
2. A Lord should be able to skip their turn at any point to reset a single center nail. This ability can only be used once during your reign as a Lord. If you are demoted and become a Lord again the ability can be used again.

Rule 1 seems like an obvious addition to me and can only serve to empower the lads and also make the game more interesting and fast paced

Rule 2 helps the pace of the game and prevents stalls, but without setting a limit I could see it potentially being abused. For example, if an uprising was about to occur a Lord could reset the center nail to hinder the next Lords. Or a Lord could constantly reset nails and make the game go on forever. Making it a limited resource would add some strategy and prevent spam

**Comment by austenlux** [comment]
I like it. Let's play test it some and then make a PR if it goes well. 👍

**Comment by austenlux** [comment]
oh I see you already made a PR
