### ISSUE TITLE
Balancing rallies + uprising rules

### ISSUE THREAD

**Issue by seanKenkeremath** [seanKenkeremath/lords-and-lads#24]
We had discussed potential balance changes around rallies and uprising. For example, in a large game rallying can be overpowered. It can allow Lads to complete an entire uprising nail in less than one turn rotation (making it very difficult for Lords to make any progress). There were a few potential balance changes we'd considered:

1. Scale up the number of uprising nails with number of players. For example, the number of uprising nails required for an uprising could be `ceiling(n/7)`
2. We could make accumulating rallies progressively more difficult depending on how many are stacked up. E.g., increasing the Rally count may only require 1 person for the first 2 rallies, but require 2 above that.
3. Lords can perform extra flips during their turn to remove rallies

There are other ways we could make this more balanced. Open to suggestions. Any thoughts?

**Comment by austenlux** [comment]
similar to 2 above, could make subsequent rallies more difficult by increasing the number of rally nails required. There's probably some clever function we can come up with similar to the function used to determine the number of Lord nails. But it would take into account the total amount of uprisings that have happened so far in that game, and the number of players (or just number of lads?), and gradually make uprisings require more nails.
