### ISSUE TITLE
There is no penalty for a Lad dropping the hammer.

### ISSUE THREAD

**Issue by austenlux** [seanKenkeremath/lords-and-lads#3]
Possible options:
- Make the Lad use their non-dominant hand the next turn.
- Make the Lad lose a turn
- Make the Lad an "Indentured Servant" of another Lad. Meaning they can only hit another Lad's nail for a pre-determined amount of time. Maybe until the nail is completely in, or maybe just 1 turn, etc. (Determining the Lad who you are Indentured to may be tricky, should probably keep it simple by just making it the next Lad to your left.)

**Comment by seanKenkeremath** [comment]
I'm not convinced a Lad should be punished for dropping the hammer. They are just a Lad after all. This also deter Lads from attempting multi flips which give existing Lords an advantage.

I'd like to hear what others think though. I could be convinced. 

Of the three options the first two could work, but my issues with the last one are 1) How do you decide who the Lad is indentured to? 2) Having them stuck on it until it's completely nailed in is way too steep of a punishment. Potentially even worse than for a Lord dropping the hammer. 3) If it is just one turn, what is to prevent the Lad from just missing on purpose?

**Comment by austenlux** [comment]
After nearly 4 years of serious thinking on this, I'd say we stick with the classic "Take a drink and lose your turn" like normal Stump.

**Comment by seanKenkeremath** [comment]
Yeah I agree with that, and that is called out in the current rules: 

`If a player fails to catch the hammer, they must drink and immediately end their turn, passing the hammer to the next play in turn order.` 

I'm going to go ahead and close this
