### ISSUE TITLE
Sparks?

### ISSUE THREAD

**Issue by seanKenkeremath** [seanKenkeremath/lords-and-lads#5]
There is nothing in the rules about sparks like there is in normal Stump. Should spark still just be a social for everyone? It seems like a rare enough occurrence that people of all social rank should drink

**Comment by austenlux** [comment]
I second this. A spark means both Lords and Lads drink.
It's like they see a comet or a solar eclipse. They interpret it as a sign....to party ☄️🍻🎉

**Comment by seanKenkeremath** [comment]
Yeah still need to add this into the rules. I'll do that after this current PR
