### ISSUE TITLE
Bonus flips when performing an Uprising

### ISSUE THREAD

**Issue by mrketchup** [seanKenkeremath/lords-and-lads#7]
If a lad performs an uprising action with extra flips (3+), how are those extra flips resolved?

Possible resolutions:
- `N - 1` flips are applied to the uprising count, with either:
  - `1` strike necessary
  - `N - 1` strikes necessary
- All extra flips are played as a normal turn
  - Example: Lad calls Uprising and flips 3 times. Lad lands (or misses) first strike which applies to the Uprising. The lad then has 1 more regular swing left to perform.

**Comment by seanKenkeremath** [comment]
Also addressing this in Uprising balance PR
